# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_boost_glasso <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, boost_umin = -5.0, verbose = 0L) {
    .Call('_abclass_r_boost_glasso', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, boost_umin, verbose)
}

r_boost_glasso_sp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, boost_umin = -5.0, verbose = 0L) {
    .Call('_abclass_r_boost_glasso_sp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, boost_umin, verbose)
}

r_boost_gmcp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, boost_umin = -5.0, verbose = 0L) {
    .Call('_abclass_r_boost_gmcp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, boost_umin, verbose)
}

r_boost_gmcp_sp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, boost_umin = -5.0, verbose = 0L) {
    .Call('_abclass_r_boost_gmcp_sp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, boost_umin, verbose)
}

r_boost_gscad <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, boost_umin = -5.0, verbose = 0L) {
    .Call('_abclass_r_boost_gscad', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, boost_umin, verbose)
}

r_boost_gscad_sp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, boost_umin = -5.0, verbose = 0L) {
    .Call('_abclass_r_boost_gscad_sp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, boost_umin, verbose)
}

r_boost_net <- function(x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, boost_umin = -5.0, verbose = 0L) {
    .Call('_abclass_r_boost_net', PACKAGE = 'abclass', x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, boost_umin, verbose)
}

r_boost_net_sp <- function(x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, boost_umin = -5.0, verbose = 0L) {
    .Call('_abclass_r_boost_net_sp', PACKAGE = 'abclass', x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, boost_umin, verbose)
}

r_hinge_boost_glasso <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_hinge_boost_glasso', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_c, verbose)
}

r_hinge_boost_glasso_sp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_hinge_boost_glasso_sp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_c, verbose)
}

r_hinge_boost_gmcp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_hinge_boost_gmcp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_c, verbose)
}

r_hinge_boost_gmcp_sp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_hinge_boost_gmcp_sp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_c, verbose)
}

r_hinge_boost_gscad <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_hinge_boost_gscad', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_c, verbose)
}

r_hinge_boost_gscad_sp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_hinge_boost_gscad_sp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_c, verbose)
}

r_hinge_boost_net <- function(x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_hinge_boost_net', PACKAGE = 'abclass', x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_c, verbose)
}

r_hinge_boost_net_sp <- function(x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_hinge_boost_net_sp', PACKAGE = 'abclass', x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_c, verbose)
}

r_logistic_glasso <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, verbose = 0L) {
    .Call('_abclass_r_logistic_glasso', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, verbose)
}

r_logistic_glasso_sp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, verbose = 0L) {
    .Call('_abclass_r_logistic_glasso_sp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, verbose)
}

r_logistic_gmcp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, verbose = 0L) {
    .Call('_abclass_r_logistic_gmcp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, verbose)
}

r_logistic_gmcp_sp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, verbose = 0L) {
    .Call('_abclass_r_logistic_gmcp_sp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, verbose)
}

r_logistic_gscad <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, verbose = 0L) {
    .Call('_abclass_r_logistic_gscad', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, verbose)
}

r_logistic_gscad_sp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, verbose = 0L) {
    .Call('_abclass_r_logistic_gscad_sp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, verbose)
}

r_logistic_net <- function(x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, verbose = 0L) {
    .Call('_abclass_r_logistic_net', PACKAGE = 'abclass', x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, verbose)
}

r_logistic_net_sp <- function(x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, verbose = 0L) {
    .Call('_abclass_r_logistic_net_sp', PACKAGE = 'abclass', x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, verbose)
}

r_lum_glasso <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_a = 1.0, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_lum_glasso', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_a, lum_c, verbose)
}

r_lum_glasso_sp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_a = 1.0, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_lum_glasso_sp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_a, lum_c, verbose)
}

r_lum_gmcp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_a = 1.0, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_lum_gmcp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_a, lum_c, verbose)
}

r_lum_gmcp_sp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_a = 1.0, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_lum_gmcp_sp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_a, lum_c, verbose)
}

r_lum_gscad <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_a = 1.0, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_lum_gscad', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_a, lum_c, verbose)
}

r_lum_gscad_sp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_a = 1.0, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_lum_gscad_sp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_a, lum_c, verbose)
}

r_lum_net <- function(x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_a = 1.0, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_lum_net', PACKAGE = 'abclass', x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_a, lum_c, verbose)
}

r_lum_net_sp <- function(x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_a = 1.0, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_r_lum_net_sp', PACKAGE = 'abclass', x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_a, lum_c, verbose)
}

r_logistic_pred_prob <- function(beta, x) {
    .Call('_abclass_r_logistic_pred_prob', PACKAGE = 'abclass', beta, x)
}

r_logistic_pred_prob_sp <- function(beta, x) {
    .Call('_abclass_r_logistic_pred_prob_sp', PACKAGE = 'abclass', beta, x)
}

r_logistic_pred_y <- function(beta, x) {
    .Call('_abclass_r_logistic_pred_y', PACKAGE = 'abclass', beta, x)
}

r_logistic_pred_y_sp <- function(beta, x) {
    .Call('_abclass_r_logistic_pred_y_sp', PACKAGE = 'abclass', beta, x)
}

r_boost_pred_prob <- function(beta, x) {
    .Call('_abclass_r_boost_pred_prob', PACKAGE = 'abclass', beta, x)
}

r_boost_pred_prob_sp <- function(beta, x) {
    .Call('_abclass_r_boost_pred_prob_sp', PACKAGE = 'abclass', beta, x)
}

r_boost_pred_y <- function(beta, x) {
    .Call('_abclass_r_boost_pred_y', PACKAGE = 'abclass', beta, x)
}

r_boost_pred_y_sp <- function(beta, x) {
    .Call('_abclass_r_boost_pred_y_sp', PACKAGE = 'abclass', beta, x)
}

r_hinge_boost_pred_prob <- function(beta, x) {
    .Call('_abclass_r_hinge_boost_pred_prob', PACKAGE = 'abclass', beta, x)
}

r_hinge_boost_pred_prob_sp <- function(beta, x) {
    .Call('_abclass_r_hinge_boost_pred_prob_sp', PACKAGE = 'abclass', beta, x)
}

r_hinge_boost_pred_y <- function(beta, x) {
    .Call('_abclass_r_hinge_boost_pred_y', PACKAGE = 'abclass', beta, x)
}

r_hinge_boost_pred_y_sp <- function(beta, x) {
    .Call('_abclass_r_hinge_boost_pred_y_sp', PACKAGE = 'abclass', beta, x)
}

r_lum_pred_prob <- function(beta, x) {
    .Call('_abclass_r_lum_pred_prob', PACKAGE = 'abclass', beta, x)
}

r_lum_pred_prob_sp <- function(beta, x) {
    .Call('_abclass_r_lum_pred_prob_sp', PACKAGE = 'abclass', beta, x)
}

r_lum_pred_y <- function(beta, x) {
    .Call('_abclass_r_lum_pred_y', PACKAGE = 'abclass', beta, x)
}

r_lum_pred_y_sp <- function(beta, x) {
    .Call('_abclass_r_lum_pred_y_sp', PACKAGE = 'abclass', beta, x)
}

