# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_abclass_fit <- function(x, y, control) {
    .Call('_abclass_rcpp_abclass_fit', PACKAGE = 'abclass', x, y, control)
}

rcpp_abclass_fit_sp <- function(x, y, control) {
    .Call('_abclass_rcpp_abclass_fit_sp', PACKAGE = 'abclass', x, y, control)
}

cv_samples <- function(nobs, nfolds, strata) {
    .Call('_abclass_cv_samples', PACKAGE = 'abclass', nobs, nfolds, strata)
}

rcpp_moml_fit <- function(x, treatment, reward, propensity_score, control) {
    .Call('_abclass_rcpp_moml_fit', PACKAGE = 'abclass', x, treatment, reward, propensity_score, control)
}

rcpp_moml_fit_sp <- function(x, treatment, reward, propensity_score, control) {
    .Call('_abclass_rcpp_moml_fit_sp', PACKAGE = 'abclass', x, treatment, reward, propensity_score, control)
}

rcpp_pred_prob <- function(beta, x, loss_id, loss_params) {
    .Call('_abclass_rcpp_pred_prob', PACKAGE = 'abclass', beta, x, loss_id, loss_params)
}

rcpp_pred_prob_sp <- function(beta, x, loss_id, loss_params) {
    .Call('_abclass_rcpp_pred_prob_sp', PACKAGE = 'abclass', beta, x, loss_id, loss_params)
}

rcpp_pred_y <- function(beta, x, loss_id) {
    .Call('_abclass_rcpp_pred_y', PACKAGE = 'abclass', beta, x, loss_id)
}

rcpp_pred_y_sp <- function(beta, x, loss_id) {
    .Call('_abclass_rcpp_pred_y_sp', PACKAGE = 'abclass', beta, x, loss_id)
}

rcpp_vertex <- function(k) {
    .Call('_abclass_rcpp_vertex', PACKAGE = 'abclass', k)
}

