# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_boost_group_lasso <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, boost_umin = -5.0, verbose = 0L) {
    .Call('_abclass_rcpp_boost_group_lasso', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, boost_umin, verbose)
}

rcpp_boost_group_mcp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, boost_umin = -5.0, verbose = 0L) {
    .Call('_abclass_rcpp_boost_group_mcp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, boost_umin, verbose)
}

rcpp_boost_group_scad <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, boost_umin = -5.0, verbose = 0L) {
    .Call('_abclass_rcpp_boost_group_scad', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, boost_umin, verbose)
}

rcpp_boost_net <- function(x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, boost_umin = -5.0, verbose = 0L) {
    .Call('_abclass_rcpp_boost_net', PACKAGE = 'abclass', x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, boost_umin, verbose)
}

rcpp_hinge_boost_group_lasso <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_rcpp_hinge_boost_group_lasso', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_c, verbose)
}

rcpp_hinge_boost_group_mcp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_rcpp_hinge_boost_group_mcp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_c, verbose)
}

rcpp_hinge_boost_group_scad <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_rcpp_hinge_boost_group_scad', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_c, verbose)
}

rcpp_hinge_boost_net <- function(x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_rcpp_hinge_boost_net', PACKAGE = 'abclass', x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_c, verbose)
}

rcpp_logistic_group_lasso <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, verbose = 0L) {
    .Call('_abclass_rcpp_logistic_group_lasso', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, verbose)
}

rcpp_logistic_group_mcp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, verbose = 0L) {
    .Call('_abclass_rcpp_logistic_group_mcp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, verbose)
}

rcpp_logistic_group_scad <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, verbose = 0L) {
    .Call('_abclass_rcpp_logistic_group_scad', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, verbose)
}

rcpp_logistic_net <- function(x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, verbose = 0L) {
    .Call('_abclass_rcpp_logistic_net', PACKAGE = 'abclass', x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, verbose)
}

rcpp_lum_group_lasso <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_a = 1.0, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_rcpp_lum_group_lasso', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_a, lum_c, verbose)
}

rcpp_lum_group_mcp <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_a = 1.0, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_rcpp_lum_group_mcp', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_a, lum_c, verbose)
}

rcpp_lum_group_scad <- function(x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_a = 1.0, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_rcpp_lum_group_scad', PACKAGE = 'abclass', x, y, lambda, nlambda, lambda_min_ratio, group_weight, dgamma, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_a, lum_c, verbose)
}

rcpp_lum_net <- function(x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept = TRUE, standardize = TRUE, nfolds = 0L, stratified_cv = TRUE, alignment = 0L, maxit = 1e5L, epsilon = 1e-3, varying_active_set = TRUE, lum_a = 1.0, lum_c = 0.0, verbose = 0L) {
    .Call('_abclass_rcpp_lum_net', PACKAGE = 'abclass', x, y, lambda, alpha, nlambda, lambda_min_ratio, weight, intercept, standardize, nfolds, stratified_cv, alignment, maxit, epsilon, varying_active_set, lum_a, lum_c, verbose)
}

rcpp_logistic_predict_prob <- function(beta, x) {
    .Call('_abclass_rcpp_logistic_predict_prob', PACKAGE = 'abclass', beta, x)
}

rcpp_logistic_predict_y <- function(beta, x) {
    .Call('_abclass_rcpp_logistic_predict_y', PACKAGE = 'abclass', beta, x)
}

rcpp_boost_predict_prob <- function(beta, x, boost_umin) {
    .Call('_abclass_rcpp_boost_predict_prob', PACKAGE = 'abclass', beta, x, boost_umin)
}

rcpp_boost_predict_y <- function(beta, x, boost_umin) {
    .Call('_abclass_rcpp_boost_predict_y', PACKAGE = 'abclass', beta, x, boost_umin)
}

rcpp_hinge_boost_predict_prob <- function(beta, x, lum_c) {
    .Call('_abclass_rcpp_hinge_boost_predict_prob', PACKAGE = 'abclass', beta, x, lum_c)
}

rcpp_hinge_boost_predict_y <- function(beta, x, lum_c) {
    .Call('_abclass_rcpp_hinge_boost_predict_y', PACKAGE = 'abclass', beta, x, lum_c)
}

rcpp_lum_predict_prob <- function(beta, x, lum_a, lum_c) {
    .Call('_abclass_rcpp_lum_predict_prob', PACKAGE = 'abclass', beta, x, lum_a, lum_c)
}

rcpp_lum_predict_y <- function(beta, x, lum_a, lum_c) {
    .Call('_abclass_rcpp_lum_predict_y', PACKAGE = 'abclass', beta, x, lum_a, lum_c)
}

